### ISSUE TITLE
Different type of Mix package

### ISSUE THREAD

**Issue by Athene-ai** [yuliadm/mixComp#6]
Hi, I am the reviewer from JOSS (https://github.com/openjournals/joss-reviews/issues/4354).

Is it possible for the author provides a better explanation of the different type of Mix package and create a demonstration on how they works

**Comment by yuliadm** [comment]
Hi @Athene-ai ! I am a bit confused about your suggestion. What is exactly meant by the different types of Mix package? Is it about the different types of functions included in the package? They are explained... The documentation.md file, the readme.md file as well as the vignettes and manuals have a very detailed explanation of each function with multiple examples on their usage... I only included the vital information  (the methodology)  to the paper.md file due to the word count restrictions. I am just not sure which of the files you mean...

**Comment by Athene-ai** [comment]
Hi @yuliadm I mean difference between  other packages, like rebmix, compared with your and why user should use your

**Comment by yuliadm** [comment]
Hello @Athene-ai, this part is done!

**Comment by Athene-ai** [comment]
Perfect 😊
